[package]
name = "quizx"
version = "0.1.0"
authors = ["Aleks Kissinger <aleks0@gmail.com>"]
edition = "2018"
default-run = "hidden_shift_stabrank"

[dependencies]
num = "0.3.1"
rustc-hash = "1.1.0"
rayon = "1.5.0"
ndarray = { version = "0.14.0", features = [ "rayon" ] }
approx = "0.4.0"
regex = "1.4.3"
rand = "0.8.3"
itertools = "0.10.1"
openqasm = "0.1.2"
glutin = { version = "0.28.0", optional = true }
femtovg = { version = "0.3.5", default-features = false, features = ["glutin"], optional = true }
winit = { version = "0.26.1", optional = true }
font-loader = { version = "0.11.0", optional = true }

[features]
editor = ["glutin", "femtovg", "winit", "font-loader"]

